out_dir: results
metric_best: auc
metric_agg: argmax
wandb:
  use: False
  project: scratch  # W&B project for debugging runs.
dataset:
  format: PyG-ZINC
  name: clintox
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_num_types: 4
  edge_encoder_bn: False
pretrained:
  dir: pretrained/pcqm4m-GPS+RWSE.deep
  reset_prediction_head: True
  freeze_main: False
train:
  mode: custom
  batch_size: 32
model:
  type: GPSModel
  loss_fun: filter_bce+bss
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: san_graph
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  batchnorm: True
  act: gelu
  dropout: 0.0
  agg: mean
